remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-sitemap
title: CustomActiveScanForZAP
show_downloads: false
description: a sofisticated SQL injection active scanner for ZAPROXY
